name: pull request check

on:
  pull_request

jobs:
  check:
    name: Check pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: "gradle"
      - name: run test
        run: |
          ./gradlew test