name: pull request check

on:
  pull_request

jobs:
  check:
    name: Check pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: run test
        run: |
          ./gradlew test